### ISSUE TITLE
Error when trying to run fom Population analyses

### ISSUE THREAD

**Issue by mrescalona** [jkimlab/PAPipe#3]
First, let me thank you for the tool.
I'm trying to run Population Analyses on a dataset that I had to process with multiple filters. In short, I'm using an assembled reference at scaffold level and low coverage data made available through GBS techniques.
When I try to run the docker, I get a python error which I cannot figure out how to fix

Traceback (most recent call last):
  File "/PAPipe/bin/main.py", line 99, in <module>
    Postprocessing.main_pipe(args, dict_param, index)
  File "/PAPipe/bin/Postprocessing.py", line 298, in main_pipe
    post_param = Param.Postprocessing(args.out, dict_param)
  File "/PAPipe/bin/Param.py", line 85, in Postprocessing
    O_post_param.write("<" + dict_param["VariantCalling"]["VCF_prefix"] + ">\n")
TypeError: can only concatenate str (not "collections.defaultdict") to str

Also, since my reference has more chromossome than allowed by plink, is there a way to add the --allow-extra-chr option from plink in the anlyses?

Any help would be appreciated.

Thank you

**Comment by timurrxxcd** [comment]
I think you are using python2. if so, try python3. in many cases these kinda problems appear in this case
let me know if u succeed

**Comment by Canglan111** [comment]
Have you solved the problem? I encountered the same error, I used the command:
python3 /PAPipe/bin/main.py -P./main_param.txt -I./main_input.txt -A./main_sample.txt.
The error message is as follows:
-----------------Start-----------------
------------Postprocessing-------------
Traceback (most recent call last):
File "/PAPipe/bin/main.py", line 99, in <module>
Postprocessing.main_pipe(args, dict_param, index)
File "/PAPipe/bin/Postprocessing.py", line 298, in main_pipe
post_param = Param.Postprocessing(args.out, dict_param)
File "/PAPipe/bin/Param.py", line 85, in Postprocessing
O_post_param.write("<" + dict_param["VariantCalling"]["VCF_prefix"] + ">\n")
TypeError: can only concatenate str (not "collections.defaultdict") to str
Thank you for your advice and help.
