### ISSUE TITLE
TypeError: can only concatenate str (not "collections.defaultdict") to str

### ISSUE THREAD

**Issue by Canglan111** [jkimlab/PAPipe#5]
I used the command:
python3 /PAPipe/bin/main.py -P./main_param.txt -I./main_input.txt -A./main_sample.txt.
The error message is as follows:
-----------------Start-----------------
------------Postprocessing-------------
Traceback (most recent call last):
File "/PAPipe/bin/main.py", line 99, in
Postprocessing.main_pipe(args, dict_param, index)
File "/PAPipe/bin/Postprocessing.py", line 298, in main_pipe
post_param = Param.Postprocessing(args.out, dict_param)
File "/PAPipe/bin/Param.py", line 85, in Postprocessing
O_post_param.write("<" + dict_param["VariantCalling"]["VCF_prefix"] + ">\n")
TypeError: can only concatenate str (not "collections.defaultdict") to str
Thank you for your advice and help.

**Comment by chapinkj** [comment]
Any update on this? Is this repo no longer maintained?

**Comment by nayoung9** [comment]
Hi, I apologize for missing this issue earlier—it must have slipped through. 
The repository is still maintained, and I'm currently looking into it. 
I'll update you soon. Thanks for your patience.

**Comment by myco-bradshaw** [comment]
Hello, I have also run into the error as well. For context my input file in a joint genotype vcf file that was called using Gatk4.

**Comment by daicy527** [comment]
Traceback (most recent call last):
  File "/PAPipe/bin/main.py", line 99, in <module>
    Postprocessing.main_pipe(args, dict_param, index)
  File "/PAPipe/bin/Postprocessing.py", line 298, in main_pipe
    post_param = Param.Postprocessing(args.out, dict_param)
  File "/PAPipe/bin/Param.py", line 85, in Postprocessing
    O_post_param.write("<" + dict_param["VariantCalling"]["VCF_prefix"] + ">\n")
TypeError: can only concatenate str (not "collections.defaultdict") to str
===============
A same error appeared (starting from a vcf.gz file).  Thank you for your advice and help.
